routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('auth/login/{user}',[\App\Http\Controllers\Auth\LoginController::class,'loginByEmail'])
->name('login.email')
->middleware(['signed','signed-url-unused']);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {

    Route::get('/auth/me', 'Auth\AuthController@me')->name('auth.me');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

    Route::get('/auto-complete/enums', 'AutoCompleteController@enums')->name('auto-complete.enums');
    Route::get('/auto-complete/customers', 'AutoCompleteController@existingCustomers')->name('auto-complete.customers');
    Route::get('/auto-complete/employees', 'AutoCompleteController@employees')->name('auto-complete.employees');
    Route::get('/auto-complete/companies', 'AutoCompleteController@companies')->name('auto-complete.companies');
    Route::get('/auto-complete/companies/{companyId}', 'AutoCompleteController@company')->name('auto-complete.company');
    Route::get('/auto-complete/persons/{personId}', 'AutoCompleteController@person')->name('auto-complete.person');

    Route::get('/auto-complete/devices', 'AutoCompleteController@devices')->name('auto-complete.devices');
    Route::get('/auto-complete/device-manufacturers', 'AutoCompleteController@manufacturers')->name('auto-complete.device-manufacturers');
    Route::get('/auto-complete/device-models', 'AutoCompleteController@models')->name('auto-complete.device-models');
    Route::get('/auto-complete/devices/{device}', 'AutoCompleteController@device')->name('auto-complete.device');
    Route::get('/auto-complete/customers/{customer}/devices', 'AutoCompleteController@previousDevices')->name('auto-complete.customer-devices');

    Route::resource('companies', 'CompanyController');
    Route::resource('customers', 'CustomerController');

    // Devices
    Route::resource('devices', 'DeviceController');




    Route::get('prints/work-items/{id}/receipt','PrintController@workItemReceipt')->name('prints.work-items.receipt');


    Route::post('work-items/{workItem}/history', [\App\Http\Controllers\WorkItemHistoryController::class,'store'])->name('work-item-history.store');
    Route::post('work-items/{workItem}/parts', [\App\Http\Controllers\PartController::class,'store'])->name('part.store');
    Route::post('work-items/{workItem}/billings', [\App\Http\Controllers\BillingController::class,'store'])->name('billing.store');
    Route::delete('parts/{id}', [\App\Http\Controllers\PartController::class,'destroy'])->name('part.destroy');


    Route::resource('work-items', 'WorkItemController');
    Route::resource('work-item-histories', 'WorkItemHistoryController');
    Route::resource('components', 'ComponentController');
    Route::resource('users', 'UserController');
    Route::resource('device-types', 'DeviceTypeController');

});

app/Http/Controllers/WorkItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\WorkItemCreateRequest;
use App\Repositories\RepositoryContracts\CompanyRepository;
use App\Repositories\RepositoryContracts\CustomerRepository;
use App\Repositories\RepositoryContracts\DeviceRepository;
use App\Repositories\RepositoryContracts\WorkItemHistoryRepository;
use App\Repositories\RepositoryContracts\WorkItemRepository;
use App\Repositories\RepositoryCriteria\ColumnTextSearch;
use App\Repositories\RepositoryCriteria\EagerLoad;
use App\Repositories\RepositoryCriteria\HasValidCustomer;
use App\Repositories\RepositoryCriteria\OrderBy;
use App\Repositories\RepositoryCriteria\WorkItem\AssignedTo;
use App\Repositories\RepositoryCriteria\WorkItem\DateRange;
use App\Repositories\RepositoryCriteria\WorkItem\IsBilled;
use App\Repositories\RepositoryCriteria\WorkItem\SignedInBy;
use App\Repositories\RepositoryCriteria\WorkItem\WithBranch;
use App\Repositories\RepositoryCriteria\WorkItem\WithPriority;
use App\Repositories\RepositoryCriteria\WorkItem\WithSupportContract;
use App\Repositories\RepositoryCriteria\WorkItem\WithStatus;
use App\Repositories\RepositoryCriteria\WorkItem\WithWarranty;
use App\ServiceManager\Branch\Branch;
use App\ServiceManager\Device\Eloquent\EloquentDevice;
use App\ServiceManager\Device\DeviceType;
use App\ServiceManager\Priority\Priority;
use App\ServiceManager\WorkItem\Eloquent\EloquentWorkItem;
use App\ServiceManager\WorkItem\WorkItem;
use App\ServiceManager\WorkItem\WorkItemUnitOfWork;
use App\Transformers\WorkItemTransformer;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use League\Fractal\Pagination\IlluminatePaginatorAdapter;

/**
 * Class WorkItemController
 * @package App\Http\Controllers
 */
class WorkItemController extends Controller
{
    protected $workItemRepository;
    protected $workItemHistoryRepository;
    protected $companyRepository;
    protected $customerRepository;
    protected $deviceRepository;
    protected $workItemTransformer;
    protected $workItemUnitOfWork;


    public function __construct(
        WorkItemUnitOfWork $workItemUnitOfWork,
        WorkItemRepository $workItemRepository,
        CompanyRepository $companyRepository,
        CustomerRepository $customerRepository,
        WorkItemHistoryRepository $workItemHistoryRepository,
        DeviceRepository $deviceRepository,
        WorkItemTransformer $workItemTransformer
    )
    {
        $this->workItemUnitOfWork = $workItemUnitOfWork;
        $this->workItemRepository = $workItemRepository;
        $this->workItemHistoryRepository = $workItemHistoryRepository;
        $this->customerRepository = $customerRepository;
        $this->companyRepository = $companyRepository;
        $this->deviceRepository = $deviceRepository;
        $this->workItemTransformer = $workItemTransformer;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //TODO - validate request vars

        $length = request()->input('length');
        $column = request()->input('column');
        $status = request()->input('status');
        $branch = request()->input('branch');
        $billed = request()->input('billed');
        $priority = request()->input('priority');
        $warranty = request()->input('warranty');
        $serviceContract = request()->input('serviceContract');
        $signedInBy = request()->input('signedInBy');
        $assignedTo = request()->input('assignedTo');
        $dateRange = request()->input('dateRange');
        $dir = request()->input('dir');
        $searchValue = request()->input('search');

        if (request()->expectsJson()) {
            $criteria = [new HasValidCustomer()];
            if ($searchValue) {
                $criteria[] = (new ColumnTextSearch())->setTerm($searchValue)->setColumns([
                    'id',
                    'customer.first_name',
                    'customer.last_name',
                    'customer.company.name',
                    'device.serial',
                    ]);
            }

            if ($column) {
                $criteria[] = (new OrderBy())->setColumn($column)->setDirection($dir ?? 'asc');
            }

            if ($status) {
                switch ($status) {
                    case 5:
                        $statuses = [1,2,3,7]; // filter to incomplete statuses ('incomplete' statuses include active, awaiting customer, awaiting parts, rma)
                        break;
                    case 999:
                        $statuses = [11,10,9,8]; // filter to billable statuses (completed, awaiting collection etc)
                        break;
                    default:
                        $statuses = [$status];
                }

                $criteria[] = (new WithStatus())->setStatuses($statuses);
            }

            if ($priority) {
                $criteria[] = (new WithPriority())->setPriorities([$priority]);
            }

            if ($branch) {
                $criteria[] = (new WithBranch())->setBranches([$branch]);
            }

            if ($signedInBy) {
                $criteria[] = (new SignedInBy())->setUserIds([$signedInBy]);
            }

            if ($assignedTo) {
                $criteria[] = (new AssignedTo())->setUserIds([$assignedTo]);
            }

            if (!is_null($billed)) {
                $criteria[] = (new IsBilled())->setBilled($billed);
            }

            if (!is_null($warranty)) {
                $criteria[] = (new WithWarranty())->setWarrantyFlag($warranty);
            }

            if (!is_null($serviceContract)) {
                $criteria[] = (new WithSupportContract())->setSupportContractFlag($serviceContract);
            }

            if ($dateRange) {
                $dateRange = json_decode($dateRange, true);
                $criteria[] = (new DateRange())->setStart(Carbon::parse($dateRange['startDate']))->setEnd(Carbon::parse($dateRange['endDate']));
            }

            $workItems = $this->workItemRepository->withCriteria(
                $criteria
            )->withRelations(['customer.company','device','history','parts','assignedTo'])->paginate($length ?? 10);

            $transformedWorkItems = fractal()
                ->collection($workItems)
                ->transformWith($this->workItemTransformer)
                ->parseIncludes(['customer.company','device','workItemHistory','assigned_to'])
                ->paginateWith(new IlluminatePaginatorAdapter($workItems))
                ->addMeta(['draw'=> request()->input('draw')])
                ->toArray();
            return response()->json($transformedWorkItems);
        }

        return view('work-items.index',['filters'=>json_encode(request()->only('status'))]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $deviceTypes = DeviceType::with('inventoryOptions')->get();
        $branches = Branch::all();
        $priorities = Priority::all();
        $manufacturers = EloquentDevice::select('manufacturer')->distinct()->get()->pluck('manufacturer');
        $models = EloquentDevice::select('model')->distinct()->get()->pluck('model');

        return view('work-items.create',[
            'models' => $models,
            'manufacturers' => $manufacturers,
            'inventory'=>$deviceTypes,
            'branches'=> $branches,
            'priorities'=>$priorities
        ]);
    }

    public function store(WorkItemCreateRequest $request)
    {
        $attributes = $request->validated();
        $attributes['workItem'] += [
                'signed_in_by'=>Auth::id(),
                'assigned_to' => null,
                'status_id' => config('settings.defaultStatus',1),
                'time' => 0,
            ];

        $workItem = $this->workItemUnitOfWork->create($attributes);
        $transformedWorkItem = $this->getTransformedWorkItem($workItem);

        return response()->json($transformedWorkItem)->setStatusCode(201);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $workItem = $this->getWorkItem($id);
        $transformedWorkItem = $this->getTransformedWorkItem($workItem);

        if (request()->expectsJson()) {
            return $transformedWorkItem;
        }
        return view('work-items.show', ['workItem' => json_encode($transformedWorkItem)]);
    }

    protected function getWorkItem($id, array $eagerLoad = null): EloquentWorkItem
    {
        $defaultEagerLoad = [
            'history',
            'customer',
            'device',
            'priority',
            'billings',
            'parts',
            'signedInBy',
            'assignedTo',
        ];
        $relations = is_array($eagerLoad) ? $eagerLoad : $defaultEagerLoad;
        return $this->workItemRepository->withRelations($relations)->find($id);
    }

    protected function getTransformedWorkItem(WorkItem $workItem)
    {
        return fractal()
            ->item($workItem)
            ->transformWith($this->workItemTransformer)
            ->parseIncludes(['customer.company','device','workItemHistory','billings','parts','signed_in_by','assigned_to'])
            ->toArray();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }


    /**
     * @param Request $request
     * @param $id
     * @return mixed
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        $validated = $this->validate($request, [
            'priority' => 'integer|exists:priorities,id',

resources/views/work-items/OLDshow.blade.php
<?php
$scripts = ['datatables'];
?>
@extends('layouts.dashboard.master')

@section('title', 'Work Item')
@push('styles')
    <style>
    </style>
@endpush

@section('breadcrumbs')
    <li class="breadcrumb-item">
        <a href="{{route('work-items.index')}}">Work Items</a>
    </li>
    <li class="breadcrumb-item active">Work Item</li>
@endsection

@section('content')
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header alt">
                    <i class="fa fa-align-justify"></i> Work Item
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <p><strong>Device:</strong> @{{workItem.device.manufacturer + ' ' + workItem.device.model}}</p>
                            <p><strong>Serial:</strong> @{{workItem.device.serial}}</p>
                            <p><strong>Password:</strong> @{{workItem.device.password}}</p>
                            <p><strong>Created At:</strong> @{{workItem.created_at | formatDate}}</p>
                            <p><strong>Signed In By:</strong> @{{workItem.signed_in_by}}</p>
                            <p><strong>Assigned To:</strong> @{{workItem.assigned_to}}</p>

                        </div>
                        <div class="col">
                            <p><strong>Branch:</strong> @{{workItem.branch ? workItem.branch.name : "Unknown"}}</p>
                            <p><strong>Company:</strong> @{{workItem.customer.company ? workItem.customer.company.name : "N/A"}}</p>
                            <p><strong>Contact:</strong> @{{workItem.customer.full_name}}</p>
                            <p><strong>Priority:</strong> @{{workItem.priority ? workItem.priority.name : 'Unknown'}}</p>
                            <p><strong>Status:</strong> @{{workItem.status ? workItem.status.name : 'Unknown'}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <p><strong>Description:</strong><br />
                                @{{workItem.issue_description}}
                            </p>

                        </div>
                    </div>
                </div>
            </div>
            <div class="card mt-5">
                <div class="card-header alt">
                    <i class="fa fa-align-justify"></i> Change History
                    <div class="card-header-actions">
                        <button class='btn btn-primary' href='#' data-toggle='modal' data-target='#newChangeModal'>Add A Change</button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card" v-for="history in workHistories">
                        <div class="card-header">
                            @{{history.changed_by.name}} said...
                            <div class="card-header-actions">
                                <small>@{{history.created_at | formatDate}}</small>
                                <span v-if="history.customer_contacted" class="badge badge-pill badge-primary ml-2">Customer Contacted</span>
                                <span class="badge badge-pill badge-success ml-2">@{{ history.time }}</span>
                            </div>
                        </div>
                        <div class="card-body">
                            @{{history.description}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <work-item-history-form
    url="{{route('work-item-histories.store')}}"
    :user = "{{\Illuminate\Support\Facades\Auth::user()}}"
    :statuses = "{{$statuses}}"
    :branches = "{{$branches}}"
    :priorities = "{{$priorities}}"
    :workItemHistory = "{{$workItem->history->first()}}"
    @created = "historyCreatedHandler"
    ></work-item-history-form>
@endsection
@push('scripts')

    <script>

        const app = new Vue({
            el: '#app',
            data: {
                workItem: @php echo $workItem @endphp,
                workHistories: @php echo $histories @endphp,
            },
            watch: {
            },
            computed: {
            },
            methods:{
                deviceSelected(device) {
                    console.log(device);
                },
                historyCreatedHandler(history) {
                    this.workHistories.unshift(history);
                    $('#newChangeModal').modal('hide');
                }
            }
        });

        $( document ).ready(function() {
            $('.datatable').DataTable({
                "ajax": "data/arrays.txt",
                "deferRender": true,
                "columns": [
                    null,
                    null,
                    null,
                    { "width": "110px" }
                ]
            });
            $('.datatable').attr('style','border-collapse: collapse !important');
        });




    </script>
@endpush

resources/views/work-items/create.blade.php
@extends('layouts.dashboard.master')

@section('title', 'Create A New Company')
@push('styles')
    <style>
        .entity-card {
            min-height: 165px;
        }
        .white-opacity-50 {
            background: rgba(255,255,255,0.5);
        }
    </style>
@endpush
@section('breadcrumbs')
    <li class="breadcrumb-item">
        <a href="{{route('work-items.index')}}">Work Items</a>
    </li>
    <li class="breadcrumb-item active">Add New</li>
@endsection

@section('content')
    <work-item-create></work-item-create>
@endsection

resources/views/work-items/index.blade.php
@extends('layouts.dashboard.master')

@section('title', 'Work Items')
@push('styles')
    <style>
    </style>
@endpush

@section('breadcrumbs')
    <li class="breadcrumb-item active">Work Items</li>
@endsection

@section('content')
<work-items-index
:filters = "{{$filters}}"
></work-items-index>
@endsection
@push('scripts')
@endpush

resources/views/work-items/show.blade.php
<?php
$scripts = ['datatables'];
?>
@extends('layouts.dashboard.master')

@section('title', 'Work Item')
@push('styles')
    <style>
    </style>
@endpush

@section('breadcrumbs')
    <li class="breadcrumb-item">
        <a href="{{route('work-items.index')}}">Work Items</a>
    </li>
    <li class="breadcrumb-item active">Work Item</li>
@endsection

@section('content')
    <work-item-show
    :work-item-object ="{{$workItem}}"
    :current-user="this.$root.currentUser"
    ></work-item-show>
@endsection

@push('scripts')
@endpush