routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('auth/login/{user}',[\App\Http\Controllers\Auth\LoginController::class,'loginByEmail'])
->name('login.email')
->middleware(['signed','signed-url-unused']);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {

    Route::get('/auth/me', 'Auth\AuthController@me')->name('auth.me');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

    Route::get('/auto-complete/enums', 'AutoCompleteController@enums')->name('auto-complete.enums');
    Route::get('/auto-complete/customers', 'AutoCompleteController@existingCustomers')->name('auto-complete.customers');
    Route::get('/auto-complete/employees', 'AutoCompleteController@employees')->name('auto-complete.employees');
    Route::get('/auto-complete/companies', 'AutoCompleteController@companies')->name('auto-complete.companies');
    Route::get('/auto-complete/companies/{companyId}', 'AutoCompleteController@company')->name('auto-complete.company');
    Route::get('/auto-complete/persons/{personId}', 'AutoCompleteController@person')->name('auto-complete.person');

    Route::get('/auto-complete/devices', 'AutoCompleteController@devices')->name('auto-complete.devices');
    Route::get('/auto-complete/device-manufacturers', 'AutoCompleteController@manufacturers')->name('auto-complete.device-manufacturers');
    Route::get('/auto-complete/device-models', 'AutoCompleteController@models')->name('auto-complete.device-models');
    Route::get('/auto-complete/devices/{device}', 'AutoCompleteController@device')->name('auto-complete.device');
    Route::get('/auto-complete/customers/{customer}/devices', 'AutoCompleteController@previousDevices')->name('auto-complete.customer-devices');

    Route::resource('companies', 'CompanyController');
    Route::resource('customers', 'CustomerController');

    // Devices
    Route::resource('devices', 'DeviceController');




    Route::get('prints/work-items/{id}/receipt','PrintController@workItemReceipt')->name('prints.work-items.receipt');


    Route::post('work-items/{workItem}/history', [\App\Http\Controllers\WorkItemHistoryController::class,'store'])->name('work-item-history.store');
    Route::post('work-items/{workItem}/parts', [\App\Http\Controllers\PartController::class,'store'])->name('part.store');
    Route::post('work-items/{workItem}/billings', [\App\Http\Controllers\BillingController::class,'store'])->name('billing.store');
    Route::delete('parts/{id}', [\App\Http\Controllers\PartController::class,'destroy'])->name('part.destroy');


    Route::resource('work-items', 'WorkItemController');
    Route::resource('work-item-histories', 'WorkItemHistoryController');
    Route::resource('components', 'ComponentController');
    Route::resource('users', 'UserController');
    Route::resource('device-types', 'DeviceTypeController');

});

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CustomerCreateRequest;
use App\Repositories\RepositoryContracts\CustomerRepository;
use App\Repositories\RepositoryCriteria\CustomerLike;
use App\Repositories\RepositoryCriteria\DeviceLike;
use App\Repositories\RepositoryCriteria\EagerLoad;
use App\Repositories\RepositoryCriteria\Latest;
use App\Repositories\RepositoryCriteria\Limit;
use App\ServiceManager\Customer\Customer;
use App\Transformers\ContactTransformer;
use App\Transformers\CustomerTransformer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class CustomerController extends Controller
{
    protected $customerRepository;

    public function __construct(CustomerRepository $customerRepository)
    {
        $this->customerRepository = $customerRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $criteria = [new Latest(), new EagerLoad(['company'])];

        if ($term = $request->get('term')) {
            $criteria[] = (new CustomerLike())->setTerm($term);
        }

        if ($pageSize = $request->get('page_size', 5)) {
            $criteria[] = new Limit($pageSize);
        }

        $devices = $this->customerRepository->withCriteria(
            $criteria
        )->get();

        $transformedCustomers = fractal()
            ->collection($devices)
            ->transformWith(new CustomerTransformer())
            ->parseIncludes(['company'])
            ->toArray();

        return response()->json($transformedCustomers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }


    public function store(CustomerCreateRequest $request)
    {
        $validatedData = $request->validated();
        $customer = $this->customerRepository->create($validatedData);
        $customer = $this->customerRepository->withRelations(['company'])->find($customer->id);
        $transformedCustomer = $this->getTransformedCustomer($customer);
        return response()->json($transformedCustomer)->setStatusCode(201);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customer = $this->getCustomer($id,['company']);
        $personTransformed = $customer->company ? $this->getTransformedContact($customer) : $this->getTransformedCustomer($customer);
        return $customer->company ?
            view('companies.contact-show',['contactJson'=>json_encode($personTransformed['data']), 'contact'=>$customer]) :
            view('customers.show',['customerJson'=>json_encode($personTransformed['data']), 'customer'=>$customer]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->customerRepository->findOrFail($id);
        $validated = $this->validate($request, [
            'first_name' => 'required|string|min:2|max:30',
            'last_name' => 'required|string|min:2|max:30',
            'address' => 'nullable|string|min:2|max:150',
            'email' => 'email|min:7|max:100',
            'home_telephone' => 'nullable|string|min:7|max:32',
            'work_telephone' => 'nullable|string|min:7|max:32',
            'mobile_telephone' => 'nullable|string|min:7|max:32',
        ]);
        $this->customerRepository->update($id,$validated);
        $customer = $this->getCustomer($id, ['company']);
        $transformedCustomer = $this->getTransformedCustomer($customer);
        return response()->json($transformedCustomer)->setStatusCode(200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    protected function getCustomer($id, array $eagerLoad = []): Customer
    {
        return $this->customerRepository->withRelations($eagerLoad)->find($id);
    }

    protected function getTransformedCustomer(Customer $customer, $includes = ['devices'], $isContact = false)
    {
        if ($customer->company) {
            $transformer = new ContactTransformer();
            $includes[] = 'company';
        } else {
            $transformer = new CustomerTransformer();

        }

        return fractal()
            ->item($customer)
            ->transformWith($transformer)
            ->parseIncludes($includes)
            ->toArray();
    }

    protected function getTransformedContact(Customer $contact, $includes = ['company'])
    {
        return $this->getTransformedCustomer($contact, $includes, true);
    }
}

resources/views/customers/vue/_component-new-customer-form.blade.php
<script>
    function getNewCompanyDefault() {
        return {
            name:"",
            address: "",
            telephone: "",

        }
    }
    function getNewCustomerFormDefaultData() {
        return {
            form: {
                contactType: 'Individual',
                submitting: false,
                errors: {},
                existingCompany: {},
                data: {
                    addNewCompany: false,
                    customer: {
                        company_id: null,
                        first_name: "",
                        last_name: "",
                        address: "",
                        email: null,
                        home_telephone: null,
                        work_telephone: null,
                        mobile_telephone: null,
                    },
                    company: {},
                },
            },
        };
    }
    Vue.component('newcustomerform', {
        data: function () {
            return getNewCustomerFormDefaultData();
        },
        watch: {
            'form.contactType': function(val,oldval){
                if(val === 'Individual') {
                    this.resetCompany();
                    this.form.data.addNewCompany = false;
                } else {
                    this.form.data.company = {};
                }
            },
        },
        methods:{
            reset() {
                Object.assign(this.$data, getNewCustomerFormDefaultData())
            },
            resetErrors() {
                this.form.errors = {};
            },
            resetCompany() {
                this.form.data.company = {};
                this.form.data.customer.company_id = null;
                this.form.existingCompany = getNewCompanyDefault();
            },
            setExistingCompany(company) {
                this.form.existingCompany = company;
                this.form.data.customer.company_id = company.id;
                this.form.data.addNewCompany = false;
            },
            showCompanyForm() {
                this.resetCompany();
                this.form.data.addNewCompany = true;
            },
            resetCustomer() {
                this.form.customer = {};
                this.resetCompany();
            },
            saveCustomer() {
                this.resetErrors();
                this.form.submitting = true;
                axios.post('{{route('customers.store')}}',
                    this.form.data
            )
            .then(response => {
                this.form.submitting = false;
                if (response.status === 200) {
                        app.setCustomer(response.data);
                        $('#newCustomerModal').modal('hide');
                        this.reset();
                    }
                })
                    .catch(e => {
                        this.form.submitting = false;
                        this.form.errors = e.response.data.errors;
                        if (e.response) {
                        }
                    })
            },
            copyCompanyAddress() {
                this.form.data.customer.address = this.form.existingCompany.address ? this.form.existingCompany.address : this.form.data.company.address ;
            },
        },
        template: `@include('customers._snippets._new-customer-form-modal')`
    });

</script>